# @format

version: "3.3"
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token $token

    networks:
      - traefik_default
networks:
  traefik_default:
    external: true
