# @format

services:
  dozzle:
    container_name: dozzle
    restart: unless-stopped
    image: amir20/dozzle:latest
    ports:
      - 9999:8080
    networks:
      - docker_network
      - socket_proxy
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: status=running
      # DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label
      DOCKER_HOST: tcp://socket-proxy:2375
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle-rtr.rule=Host(`$host`)
      - traefik.http.routers.dozzle-rtr.entrypoints=websecure
      - traefik.http.routers.dozzle-rtr.middlewares=chain-oauth@file
      - traefik.http.routers.dozzle-rtr.service=dozzle-svc
      - traefik.http.services.dozzle-svc.loadbalancer.server.port=8080
networks:
  docker_network:
    external: true
  socket_proxy:
    external: true
