# @format

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=info
      - TZ=Asia/Tokyo
      - TEST_URL=https://www.google.com
    restart: unless-stopped
    networks:
      - dockge_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.flaresolverr-rtr.rule=Host(`$host`)
      - traefik.http.routers.flaresolverr-rtr.entrypoints=websecure
      - traefik.http.routers.flaresolverr-rtr.middlewares=chain-no-auth@file
      - traefik.http.services.flaresolverr-svc.loadbalancer.server.port=8191
      - traefik.http.routers.flaresolverr-rtr.service=flaresolverr-svc
networks:
  dockge_default:
    external: true
