# @format

services:
  flaresolverr:
    image: 21hsmw/flaresolverr:nodriver
    restart: unless-stopped
    container_name: flaresolverr
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Tokyo
      - NAME_SERVERS=1.1.1.1
      - LANG=en-US
    networks:
      - docker_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.flaresolverr-rtr.rule=Host(`$host`)
      - traefik.http.routers.flaresolverr-rtr.entrypoints=websecure
      - traefik.http.routers.flaresolverr-rtr.middlewares=chain-no-auth@file
      - traefik.http.services.flaresolverr-svc.loadbalancer.server.port=8191
      - traefik.http.routers.flaresolverr-rtr.service=flaresolverr-svc
networks:
  docker_network:
    external: true
