# @format

services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=3000
      - PGID=568
      - TZ=Asia/Tokyo
    volumes:
      - /mnt/overseer/config:/config
    ports:
      - 5055:5055
    networks:
      - dockge_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.overseerr-rtr.rule=Host(`$host`)
      - traefik.http.routers.overseerr-rtr.entrypoints=websecure
      - traefik.http.routers.overseerr-rtr.middlewares=chain-no-auth@file
      - traefik.http.routers.overseerr-rtr.service=overseerr-svc
      - traefik.http.services.overseerr-svc.loadbalancer.server.port=5055
    restart: unless-stopped
networks:
  dockge_default:
    external: true
