# @format

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: plex
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - /mnt/plex/config:/config
      - /mnt/plex/transcode:/transcode
      - /mnt/plex/library_files:/library
    networks:
      - traefik_default
    environment:
      - PUID=3000
      - PGID=568
      - TZ=Asia/Tokyo
      - PLEX_CLAIM=$PLEX_CLAIM
    devices:
      - /dev/dri:/dev/dri
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.rule=Host(`$host`)
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.routers.plex.tls.certresolver=cloudflare
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.protocol=https
    restart: unless-stopped
networks:
  traefik_default:
    external: true
