# @format

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=3000
      - PGID=568
      - TZ=Asia/Tokyo
      - WEBUI_PORT=10095
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/qbittorrent/config:/config
      - /mnt/qbittorrent/files:/torrents
    ports:
      - 10095:10095
      - 6881:6881
      - 6881:6881/udp
    networks:
      - dockge_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent-rtr.rule=Host(`$host`)
      - traefik.http.routers.qbittorrent-rtr.entrypoints=websecure
      - traefik.http.routers.qbittorrent-rtr.middlewares=chain-no-auth@file
      - traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc
      - traefik.http.services.qbittorrent-svc.loadbalancer.server.port=10095
    restart: unless-stopped
networks:
  dockge_default:
    external: true
