# @format

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=3000
      - PGID=568
      - TZ=Asia/Tokyo
    volumes:
      - /mnt/radarr/config:/config
      - /mnt/plex:/library
      - /mnt/qbittorrent/files:/torrents
    networks:
      - dockge_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr-rtr.rule=Host(`$host`)
      - traefik.http.routers.radarr-rtr.entrypoints=websecure
      - traefik.http.routers.radarr-rtr.middlewares=chain-no-auth@file
      - traefik.http.routers.radarr-rtr.service=radarr-svc
      - traefik.http.services.radarr-svc.loadbalancer.server.port=7878
    ports:
      - 7878:7878
    restart: unless-stopped
networks:
  dockge_default:
    external: true
