# @format

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=3000
      - PGID=568
      - TZ=Asia/Tokyo
    volumes:
      - /mnt/sonarr/config:/config
      - /mnt/plex:/library
      - /mnt/qbittorrent/files:/torrents
    ports:
      - 8989:8989
    networks:
      - docker_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr-rtr.rule=Host(`$host`)
      - traefik.http.routers.sonarr-rtr.entrypoints=websecure
      - traefik.http.routers.sonarr-rtr.middlewares=chain-no-auth@file
      - traefik.http.routers.sonarr-rtr.service=sonarr-svc
      - traefik.http.services.sonarr-svc.loadbalancer.server.port=8989
    restart: unless-stopped
networks:
  docker_network:
    external: true
